name: Firebase CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures the entire git history is checked out
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use Node.js 20
        cache: 'npm'
    
    - name: Check for Dependencies Lock File
      run: |
        if [ ! -f package-lock.json ] && [ ! -f yarn.lock ]; then
          echo "No lock file found. Please ensure package-lock.json or yarn.lock is present."
          exit 1
        fi
    
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      run: npm run build  # Customize this command as necessary

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
